In [31]:
import pandas as pd
import json
import ast 
#importar dataset
movies=pd.read_csv('movies_dataset.csv',sep=',')
movies.head()

C:\Users\Jose\AppData\Local\Temp\ipykernel_13924\545809220.py:5: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies=pd.read_csv('movies_dataset.csv',sep=',')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [32]:
def convertir1(object):  ## funciona con genres, 
    Lista = []
    for i in ast.literal_eval(object):
        Lista.append(i['name'])
    return Lista

movies["genres"]=movies["genres"].apply(convertir1) #desanidamos genres y extraemos names

In [33]:
#esta funcion sirve para lista de diccionarios con string
def convertir2(obj): 
    
    if isinstance(obj, str) and '{' in obj:
        dic = ast.literal_eval(obj)

        return dic['name']
## desanido bellongs
movies['belongs_to_collection'] = movies['belongs_to_collection'].apply(convertir2)

In [34]:
#desanidar production_companies
def convertir3(obj): 
    if isinstance(obj, str) and '{' in obj:
        L=[]
        for i in ast.literal_eval(obj):
            L.append(i['name']);
        return L
movies['production_companies'] = movies['production_companies'].apply(convertir3)

In [35]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,Toy Story Collection,30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,None,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,Grumpy Old Men Collection,0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,None,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,Father of the Bride Collection,0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [36]:
#reemplazamos los valores nulos de las columnas budget y revenue por cero en nuestro data frame movies 2
movies['budget']=movies['budget'].fillna(0)
movies['revenue']=movies['revenue'].fillna(0)

In [37]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,Toy Story Collection,30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,None,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,Grumpy Old Men Collection,0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,None,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,Father of the Bride Collection,0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [38]:
#se eliminan los valor nulos de la columna release date
movies=movies.dropna(subset=['release_date'])

In [39]:
#estos valores no tenian sentido dentro del dataframe por lo tanto pocedo a eliminarlos

movies=movies.drop(movies[movies['release_date']=='False'].index)
movies=movies.drop(movies[movies['release_date']=='Warlock'].index)
movies=movies.drop(movies[movies['release_date']=='Kung Pow: Enter the Fist'].index)
movies=movies.drop(movies[movies['release_date']==1].index)
movies=movies.drop(movies[movies['release_date']=='1'].index)
movies=movies.drop(movies[movies['release_date']==13].index)
movies=movies.drop(movies[movies['release_date']==2].index)
movies=movies.drop(movies[movies['release_date']==5.0].index)
movies=movies.drop(movies[movies['release_date']==4.6].index)
movies=movies.drop(movies[movies['release_date']==7.3].index)
movies=movies.drop(movies[movies['release_date']==6.6].index)
movies=movies.drop(movies[movies['release_date']==5.1].index)
movies=movies.drop(movies[movies['release_date']==6.4].index)
movies=movies.drop(movies[movies['release_date']=='/xGiaXH17qJyk5cy2gRcHJvEGIqZ.jpg'].index)
movies=movies.drop(movies[movies['release_date']=='Beauty and the Bastard'].index)
movies=movies.drop(movies[movies['release_date']=='Bye-Bye Bin Laden'].index)
movies=movies.drop(movies[movies['release_date']=='/u6YDFe0ix9hMtQeD4ASOXC15I21.jpg'].index)
movies=movies.drop(movies[movies['release_date']=='Trog'].index)
movies = movies.drop(movies[movies['release_date'] == 0].index)

In [40]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,Toy Story Collection,30000000,"[Animation, Comedy, Family]",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,None,65000000,"[Adventure, Fantasy, Family]",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,Grumpy Old Men Collection,0,"[Romance, Comedy]",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,None,16000000,"[Comedy, Drama, Romance]",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,Father of the Bride Collection,0,[Comedy],NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [41]:
#le damos formate de fecha a la columna de release_dae
movies['release_date']=pd.to_datetime(movies['release_date'],format='%Y-%m-%d',errors='coerce')

In [42]:
#crear la columna release_year
movies['release_year']=movies['release_date'].dt.year

In [43]:
#convertimos los datos en datos numericos para realizar las operaciones
import numpy as np  
movies['revenue']=pd.to_numeric(movies['revenue'],errors='coerce')
movies['budget']=pd.to_numeric(movies['budget'],errors='coerce')

In [44]:
#creamos la columna return con la operacion que se indico.
movies['return']=movies['revenue']/movies['budget']
movies['return']=movies['return'].fillna(0)
movies['return'].head()

0    12.451801
1     4.043035
2     0.000000
3     5.090760
4          inf
Name: return, dtype: float64

In [45]:
movies['poster_path'].head()

0    /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1    /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2    /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3    /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4    /e64sOI48hQXyru7naBFyssKFxVd.jpg
Name: poster_path, dtype: object

In [46]:
#eliminamos las columnas innecesarias. 
movies=movies.drop(['video','imdb_id','adult','original_title','vote_count','poster_path','homepage'],axis=1)

In [47]:
movies.head()

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return
0,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,[Pixar Animation Studios],"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,1995.0,12.451801
1,None,65000000.0,"[Adventure, Fantasy, Family]",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[TriStar Pictures, Teitler Film, Interscope Co...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,1995.0,4.043035
2,Grumpy Old Men Collection,0.0,"[Romance, Comedy]",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[Warner Bros., Lancaster Gate]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,1995.0,0.000000
3,None,16000000.0,"[Comedy, Drama, Romance]",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[Twentieth Century Fox Film Corporation],"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,1995.0,5.090760
4,Father of the Bride Collection,0.0,[Comedy],11862,en,Just when George Banks has recovered from his ...,8.387519,"[Sandollar Productions, Touchstone Pictures]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,1995.0,inf

In [48]:
#primera funcion
def peliculas_mes(movies, mes):
    # Diccionario para convertir el nombre del mes en espaÃ±ol a su nÃºmero
    meses = {'enero': 1, 'febrero': 2, 'marzo': 3, 'abril': 4, 'mayo': 5, 'junio': 6,
             'julio': 7, 'agosto': 8, 'septiembre': 9, 'octubre': 10, 'noviembre': 11, 'diciembre': 12}
    # Convierte el nombre del mes en espaÃ±ol a su nÃºmero
    mes_numero = meses.get(mes.lower())
    # Verifica si el mes es vÃ¡lido
    if mes_numero is None:
        return f"Error: Mes '{mes}' no vÃ¡lido"
    # Filtra el DataFrame por el mes especificado
    filtro = movies[movies['release_date'].dt.month == mes_numero]
    # Cuenta el nÃºmero de pelÃ­culas
    count = filtro['title'].count()
    # Devuelve el resultado en el formato especificado
    result = {'mes': mes.capitalize(), 'cantidad': count}
    return result

In [49]:
result = peliculas_mes(movies, 'junio')
print(result)

{'mes': 'Junio', 'cantidad': 3153}

In [50]:
def peliculas_dia(dia):
    # Crea una lista con los dÃ­as de la semana en espaÃ±ol
    dias = ['lunes', 'martes', 'miÃ©rcoles', 'jueves', 'viernes', 'sÃ¡bado', 'domingo']
    # Encuentra el Ã­ndice del dÃ­a especificado en la lista de dÃ­as
    dia_index = dias.index(dia.lower())
    # Crea una columna con el dÃ­a de la semana en el DataFrame
    movies['dia_semana'] = movies['release_date'].dt.dayofweek
    # Filtra el DataFrame por el dÃ­a especificado
    filtro = movies[movies['dia_semana'] == dia_index]
    # Cuenta el nÃºmero total de pelÃ­culas
    count = filtro['title'].count()
    # Devuelve el resultado en el formato especificado
    result = {'dia': dia.capitalize(), 'cantidad': count}
    return result

In [51]:
result = peliculas_dia('lunes')
print(result)

{'dia': 'Lunes', 'cantidad': 3503}

In [52]:
#tercera funcion
def franquicia(movies, franquicia):
    # Filtra el DataFrame por la franquicia especificada
    filtro = movies[movies['belongs_to_collection'] == franquicia]
    # Cuenta el nÃºmero de pelÃ­culas
    cantidad = filtro['title'].count()
    # Calcula la ganancia total
    ganancia_total = filtro['revenue'].sum()
    # Calcula la ganancia promedio
    ganancia_promedio = filtro['revenue'].mean()
    # Devuelve el resultado en el formato especificado
    result = {'franquicia': franquicia,
              'cantidad': cantidad,
              'ganancia_total': ganancia_total,
              'ganancia_promedio': ganancia_promedio}
    return result

In [53]:
result = franquicia(movies, 'Toy Story Collection')
print(result)

{'franquicia': 'Toy Story Collection', 'cantidad': 3, 'ganancia_total': 1937890605.0, 'ganancia_promedio': 645963535.0}

In [54]:
movies.head()

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return,dia_semana
0,Toy Story Collection,30000000.0,"[Animation, Comedy, Family]",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,[Pixar Animation Studios],"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,1995.0,12.451801,0.0
1,None,65000000.0,"[Adventure, Fantasy, Family]",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[TriStar Pictures, Teitler Film, Interscope Co...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,1995.0,4.043035,4.0
2,Grumpy Old Men Collection,0.0,"[Romance, Comedy]",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[Warner Bros., Lancaster Gate]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,1995.0,0.000000,4.0
3,None,16000000.0,"[Comedy, Drama, Romance]",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[Twentieth Century Fox Film Corporation],"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,1995.0,5.090760,4.0
4,Father of the Bride Collection,0.0,[Comedy],11862,en,Just when George Banks has recovered from his ...,8.387519,"[Sandollar Productions, Touchstone Pictures]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,1995.0,inf,4.0

In [55]:
def save_jason_loads(s):
    try:
        return json.loads(s)
    except:
        return None

In [56]:
movies["production_companies"] = movies["production_companies"].apply(lambda x: str(x))
movies["production_companies"] = movies["production_companies"].str.replace("'", '"')
movies["production_companies"] = movies["production_companies"] .astype(str)

df_pc_dict = movies["production_companies"].apply(save_jason_loads)
# Convertir el diccionario a un DataFrame
df_pc = pd.json_normalize(df_pc_dict)

In [57]:
movies=movies.dropna()

In [58]:
def aplanar(columna):
    L = []
    if isinstance(columna, str):
        for i in ast.literal_eval(columna):
            L.append(i['name'])
    return L

In [ ]:
movies['production_countries']=movies3['production_countries'].apply(aplanar)

C:\Users\Jose\AppData\Local\Temp\ipykernel_2184\1669800579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['production_countries']=movies3['production_countries'].apply(aplanar)

In [ ]:
movies.head()

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,release_year,return,dia_semana
2,Grumpy Old Men Collection,0.0,"[Romance, Comedy]",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[Warner Bros., Lancaster Gate]",[],1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,1995.0,0.000000,4.0
4,Father of the Bride Collection,0.0,[Comedy],11862,en,Just when George Banks has recovered from his ...,8.387519,"[Sandollar Productions, Touchstone Pictures]",[],1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,1995.0,inf,4.0
9,James Bond Collection,58000000.0,"[Adventure, Action, Thriller]",710,en,James Bond must unmask the mysterious head of ...,14.686036,"[United Artists, Eon Productions]",[],1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,6.6,1995.0,6.072311,3.0
12,Balto Collection,0.0,"[Family, Animation, Adventure]",21032,en,An outcast half-wolf risks his life to prevent...,12.140733,"[Universal Pictures, Amblin Entertainment, Amb...",[],1995-12-22,11348324.0,78.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Part Dog. Part Wolf. All Hero.,Balto,7.1,1995.0,inf,4.0
18,Ace Ventura Collection,30000000.0,"[Crime, Comedy, Adventure]",9273,en,"Summoned from an ashram in Tibet, Ace finds hi...",8.205448,"[O Entertainment, Warner Bros., Morgan Creek P...",[],1995-11-10,212385533.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,New animals. New adventures. Same hair.,Ace Ventura: When Nature Calls,6.1,1995.0,7.079518,4.0

In [66]:
def peliculas_pais(pais):
    '''Ingresas el pais, retornando la cantidad de peliculas producidas en el mismo'''
    cantidad = sum(movies['production_countries'].apply(lambda x: pais in x))
    return {'pais':pais, 'cantidad':cantidad}

In [68]:
resultado = peliculas_pais('United States of America')
print(resultado)

{'pais': 'United States of America', 'cantidad': 1999}

In [ ]:
def productoras(movies, productora):
    # Filtra el DataFrame por la productora especificada
    filtro = movies[movies['production_companies'].apply(lambda x: productora in x)]
    # Cuenta el nÃºmero de pelÃ­culas
    cantidad = filtro['title'].count()
    # Calcula la ganancia total
    ganancia_total = filtro['revenue'].sum()
    # Devuelve el resultado en el formato especificado
    result = {'productora': productora,
              'cantidad': cantidad,
              'ganancia_total': ganancia_total}
    return result

In [ ]:
result = productoras(movies, 'Pixar Animation Studios')
print(result)

{'productora': 'Pixar Animation Studios', 'cantidad': 10, 'ganancia_total': 6843066554.0}

In [ ]:
def retorno(df, pelicula):
    '''Ingresas la pelicula, retornando la inversion, la ganancia, el retorno y el aÃ±o en el que se lanzo'''
    mask = df['title'] == pelicula
    inversion = df[mask]['budget'].sum()
    ganancia = df[mask]['revenue'].sum()
    retorno = (ganancia - inversion) / inversion if inversion != 0 else 0
    anio = df[mask]['release_year'].sum()
    return {'pelicula':pelicula, 'inversion':inversion, 'ganancia':ganancia,'retorno':retorno, 'anio':anio}

In [ ]:
resultado = retorno(movies, 'Grumpier Old Men')
print(resultado)

{'pelicula': 'Grumpier Old Men', 'inversion': 0.0, 'ganancia': 0.0, 'retorno': 0, 'anio': 1995.0}

In [60]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer

# Primero, crear matrices binarias que representen los gÃ©neros y las compaÃ±Ã­as de producciÃ³n de cada pelÃ­cula
genres = movies['genres']
mlb = MultiLabelBinarizer()
genres_encoded = mlb.fit_transform(genres)

production_companies = movies['production_companies']
mlb = MultiLabelBinarizer()
production_companies_encoded = mlb.fit_transform(production_companies)

# Luego,  concatenar las matrices para obtener una matriz de caracterÃ­sticas para cada pelÃ­cula
features = np.concatenate([genres_encoded, production_companies_encoded], axis=1)

# Luego, calcular la similitud entre todas las pelÃ­culas utilizando la distancia del coseno
similarity_matrix = cosine_similarity(features)

# Finalmente, definir una funciÃ³n que tome el tÃ­tulo de una pelÃ­cula y devuelva las 5 pelÃ­culas mÃ¡s similares
def get_similar_movies(title):
    # Obtenemos el Ã­ndice de la pelÃ­cula en el dataframe
    idx = movies[movies['title'] == title].index[0]
    # Obtenemos las similitudes con todas las demÃ¡s pelÃ­culas
    similarities = similarity_matrix[idx]
    # Ordenamos las pelÃ­culas por similitud y seleccionamos las 5 mÃ¡s similares
    similar_movies_idx = np.argsort(similarities)[::-1][1:6]
    similar_movies = movies.iloc[similar_movies_idx]['title']
    return similar_movies.tolist()